### ISSUE TITLE
你好，我down下來，不 能運行

### ISSUE THREAD

**Issue by yanshinian** [Ihavee/ihavee.github.io#1]
我搞錯了，可以運行，貌似，這不是你最全的吧，我見分類列表沒有東西！
我是剛開始玩jekyll，多多指教！

**Comment by Havanna** [comment]
https://gitcafe.com/Havee/Havee

**Comment by LeaderQiu** [comment]
yanshinian,nice proj

**Comment by yanshinian** [comment]
非常感謝 @Havanna
